sudo: required

# Install Docker
services:
  - docker

# Execute logic
script:
  - echo "Hello Everyone!"

after_success:
  # Build all the docker files
  - docker build -t mshravan/zomato-client ./client
  - docker build -t mshravan/zomato-server ./server
  - docker build -t mshravan/zomato-nginx ./nginx

  # log in docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push to docker hub
  - docker push mshravan/zomato-client
  - docker push mshravan/zomato-server
  - docker push mshravan/zomato-nginx